# Import smtplib for the actual sending function
import smtplib

# Import the email modules we'll need
from email.message import EmailMessage

from string import Template
from pathlib import Path

html = Template(Path('index.html').read_text())


email = EmailMessage()
email['from'] = 'SENDER_EMAIL'
email['to'] = 'RECEIVER_EMAIL'
email['subject'] = 'YOUR_MESSAGE'

email.set_content(html.substitute({'name': 'NAME'}), 'html')

with smtplib.SMTP(host='smtp.gmail.com', port= 25) as smtp:
	smtp.ehlo()
	smtp.starttls()
	smtp.login('YOUR_MAIL','YOURPASSWORD')
	smtp.send_message(email)
	print('all was good boss!')


# # The first step is always the same: import all necessary components:
# import smtplib
# from socket import gaierror

# # Now you can play with your code. Let’s define the SMTP server separately here:
# port = 2525
# smtp_server = "smtp.mailtrap.io"
# login = "1a2b3c4d5e6f7g" # paste your login generated by Mailtrap
# password = "1a2b3c4d5e6f7g" # paste your password generated by Mailtrap

# # Specify the sender’s and receiver’s email addresses:
# sender = "from@example.com"
# receiver = "mailtrap@example.com"

# # Type your message: use two newlines (\n) to separate the subject from the message body, and use 'f' to  automatically insert variables in the text
# message = f"""\
# Subject: Hi Mailtrap
# To: {receiver}
# From: {sender}
# This is my first message with Python."""

# try:
#   # Send your message with credentials specified above
#   with smtplib.SMTP(smtp_server, port) as server:
#     server.login(login, password)
#     server.sendmail(sender, receiver, message)
# except (gaierror, ConnectionRefusedError):
#   # tell the script to report if your message was sent or which errors need to be fixed
#   print('Failed to connect to the server. Bad connection settings?')
# except smtplib.SMTPServerDisconnected:
#   print('Failed to connect to the server. Wrong user/password?')
# except smtplib.SMTPException as e:
#   print('SMTP error occurred: ' + str(e))
# else:
#   print('Sent')